### ISSUE TITLE
Reponse.body().close() issue

### ISSUE THREAD

**Issue by lrodriguezds** [talon-one/TalonOneJavaSdk#4]
We've found a possible bug in java sdk.
The problem is in IntegrationApiClient.handleResponse() method. You are closing just responses with returnType == null OR response code == 204.
When the response was successful (200) and already deserialized we also need to close the response.

Do not closing the response body can lead a lack of performance.
OkHttp documentation says:
> To facilitate connection recycling, callers should always close the response body

https://github.com/talon-one/TalonOneJavaSdk/blob/a6e6d439513b6f51b5388f0d508c1417b9342eb0/src/main/java/one/talon/api/IntegrationApiClient.java#L920

**Comment by lrodriguezds** [comment]
Same thing is happening in ManagementApiClient.handleResponse()

**Comment by aungerh** [comment]
Hi @lrodriguezds ! thanks for the issue report.

> Do not closing the response body can lead a lack of performance.
> OkHttp documentation says:
>
> To facilitate connection recycling, callers should always close the response body

I see why it could be a possible bug, but mind ["the response body is a one-shot value that may be consumed only once and then closed. All other properties are immutable"](https://square.github.io/okhttp/3.x/okhttp/okhttp3/Response.html)

Those 2 exceptions in which the body is closed is because there is actually nothing to read from the response body; if we close the body then you won't be able to read it no longer. Following the execution trace there's this instruction on `deserialize`

https://github.com/talon-one/TalonOneJavaSdk/blob/a6e6d439513b6f51b5388f0d508c1417b9342eb0/src/main/java/one/talon/api/IntegrationApiClient.java#L707

and according to okhttp docs, this method has a nice side effect, it closes the body automatically:

> Returns the response as a string decoded with the charset of the Content-Type header. If that header is either absent or lacks a charset, this will attempt to decode the response body in accordance to its BOM or UTF-8. Closes ResponseBody automatically.

Is it sinking performance on your end?

**Comment by lrodriguezds** [comment]
Hi @aungerh thanks for you reply!
You are right, that `string()` method will close the body. I didn't see that.
Keep in mind that Sdk is using okhttp v2.7.5 and the documentation linked was for v3.x (it doesn't matter for this issue).

We are trying to increase the performance and reduce the latency as far as we can.

Is it in your roadmap support okhttp 3.x?
